// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customer (
    name
) VALUES (
    $1
)
RETURNING id, name, datastore, created_at, updated_at
`

func (q *Queries) CreateCustomer(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Datastore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTokenUsage = `-- name: CreateTokenUsage :one
INSERT INTO token_usage (
    id, customer_id, model, input_tokens, output_tokens, total_tokens
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id)
DO UPDATE SET
    customer_id = EXCLUDED.customer_id,
    model = EXCLUDED.model,
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    total_tokens = EXCLUDED.total_tokens
RETURNING id, customer_id, model, input_tokens, output_tokens, total_tokens, created_at
`

type CreateTokenUsageParams struct {
	ID           pgtype.UUID
	CustomerID   int64
	Model        string
	InputTokens  int32
	OutputTokens int32
	TotalTokens  int32
}

func (q *Queries) CreateTokenUsage(ctx context.Context, arg CreateTokenUsageParams) (TokenUsage, error) {
	row := q.db.QueryRow(ctx, createTokenUsage,
		arg.ID,
		arg.CustomerID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
	)
	var i TokenUsage
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customer
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, datastore, created_at, updated_at FROM customer
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Datastore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByName = `-- name: GetCustomerByName :one
SELECT id, name, datastore, created_at, updated_at FROM customer
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetCustomerByName(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByName, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Datastore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerRootFolder = `-- name: GetCustomerRootFolder :one
SELECT id, parent_id, customer_id, title, created_at, updated_at FROM folder
WHERE customer_id = $1 AND parent_id = NULL
`

func (q *Queries) GetCustomerRootFolder(ctx context.Context, customerID int64) (Folder, error) {
	row := q.db.QueryRow(ctx, getCustomerRootFolder, customerID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CustomerID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, parent_id, customer_id, filename, type, size_bytes, sha_256, created_at FROM document
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CustomerID,
		&i.Filename,
		&i.Type,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentsByCustomer = `-- name: GetDocumentsByCustomer :many
SELECT id, parent_id, customer_id, filename, type, size_bytes, sha_256, created_at FROM document
WHERE customer_id = $1
`

func (q *Queries) GetDocumentsByCustomer(ctx context.Context, customerID int64) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CustomerID,
			&i.Filename,
			&i.Type,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsFromParent = `-- name: GetDocumentsFromParent :many
SELECT id, parent_id, customer_id, filename, type, size_bytes, sha_256, created_at FROM document
where parent_id = $1
`

func (q *Queries) GetDocumentsFromParent(ctx context.Context, parentID int64) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsFromParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CustomerID,
			&i.Filename,
			&i.Type,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolder = `-- name: GetFolder :one
SELECT id, parent_id, customer_id, title, created_at, updated_at FROM folder
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFolder(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CustomerID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoldersByCustomer = `-- name: GetFoldersByCustomer :many
SELECT id, parent_id, customer_id, title, created_at, updated_at FROM folder
WHERE customer_id = $1
`

func (q *Queries) GetFoldersByCustomer(ctx context.Context, customerID int64) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CustomerID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoldersFromParent = `-- name: GetFoldersFromParent :many
SELECT id, parent_id, customer_id, title, created_at, updated_at FROM folder
WHERE parent_id = $1
`

func (q *Queries) GetFoldersFromParent(ctx context.Context, parentID int64) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersFromParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CustomerID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenUsage = `-- name: GetTokenUsage :many
SELECT id, customer_id, model, input_tokens, output_tokens, total_tokens, created_at FROM token_usage
WHERE customer_id = $1
`

func (q *Queries) GetTokenUsage(ctx context.Context, customerID int64) ([]TokenUsage, error) {
	rows, err := q.db.Query(ctx, getTokenUsage, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenUsage
	for rows.Next() {
		var i TokenUsage
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, datastore, created_at, updated_at FROM customer
ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Datastore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customer
    set name = $2
WHERE id = $1
RETURNING id, name, datastore, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.Exec(ctx, updateCustomer, arg.ID, arg.Name)
	return err
}
