version: '3.8'

services:
  aicontent-db:
    build: .
    container_name: aicontent-db
    ports:
      - "5432:5432" # Map PostgreSQL default port to host
    volumes:
      - ./data:/var/lib/postgresql/data # Mount host data directory to the container
      - ./schema/00_GENERATED_schema.sql:/docker-entrypoint-initdb.d/init.sql # Mount init script
    environment:
      POSTGRES_PASSWORD: aicontent
      POSTGRES_USER: aicontent
      POSTGRES_DB: aicontent
    networks:
      - postgres-net

networks:
  postgres-net:

volumes:
  data: